import type { Question } from '@api/questions'

export const MOCK_BACKLOG: Question[] = [
  {
    _id: 'mock-1',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'Two Sum',
    status: 'pending',
    difficulty: 'easy',
    topic: 'dsa',
    source: 'leetcode',
    url: 'https://leetcode.com/problems/two-sum/',
    tags: ['array', 'hash-map'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    _id: 'mock-2',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'LRU Cache',
    status: 'pending',
    difficulty: 'medium',
    topic: 'dsa',
    source: 'leetcode',
    url: 'https://leetcode.com/problems/lru-cache/',
    tags: ['linked-list', 'hash-map'],
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    _id: 'mock-3',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'Design a URL Shortener',
    status: 'in_progress',
    difficulty: 'hard',
    topic: 'system_design',
    tags: ['scalability', 'database'],
    createdAt: '2024-01-17T10:00:00Z',
    updatedAt: '2024-01-17T10:00:00Z',
  },
  {
    _id: 'mock-4',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'Tell me about a time you led a project',
    status: 'pending',
    topic: 'behavioral',
    tags: ['leadership'],
    createdAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
  },
  {
    _id: 'mock-5',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'Build a Star Rating Component',
    status: 'pending',
    difficulty: 'medium',
    topic: 'machine_coding',
    source: 'greatfrontend',
    url: 'https://greatfrontend.com/questions/star-rating',
    tags: ['react', 'components'],
    createdAt: '2024-01-19T10:00:00Z',
    updatedAt: '2024-01-19T10:00:00Z',
  },
  {
    _id: 'mock-6',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'Merge K Sorted Lists',
    status: 'solved',
    difficulty: 'hard',
    topic: 'dsa',
    source: 'leetcode',
    url: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    tags: ['heap', 'linked-list'],
    solvedAt: '2024-01-20T15:00:00Z',
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-20T15:00:00Z',
  },
  {
    _id: 'mock-7',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'Implement Promise.all',
    status: 'pending',
    difficulty: 'medium',
    topic: 'language_framework',
    source: 'greatfrontend',
    tags: ['javascript', 'promises'],
    createdAt: '2024-01-21T10:00:00Z',
    updatedAt: '2024-01-21T10:00:00Z',
  },
  {
    _id: 'mock-8',
    taskInstance: null,
    task: null,
    userId: 'mock',
    title: 'Design a Chat System',
    status: 'pending',
    difficulty: 'hard',
    topic: 'system_design',
    tags: ['websockets', 'real-time'],
    createdAt: '2024-01-22T10:00:00Z',
    updatedAt: '2024-01-22T10:00:00Z',
  },
]
